namespace Chroma.Extensibility
{
    public enum HookPoint
    {
        Draw,
        Update,
        FixedUpdate,
        LoadContent,
        MouseMoved,
        MousePressed,
        MouseReleased,
        WheelMoved,
        TouchMoved,
        TouchPressed,
        TouchReleased,
        MultiGesture,
        KeyPressed,
        KeyReleased,
        TextInput,
        ControllerConnected,
        ControllerDisconnected,
        ControllerButtonPressed,
        ControllerButtonReleased,
        ControllerAxisMoved,
        ControllerTouchpadMoved,
        ControllerTouchpadTouched,
        ControllerTouchpadReleased,
        ControllerGyroscopeStateChanged,
        ControllerAccelerometerStateChanged
    }
}